(in-package #:area51)

(defun scaffold-config (name dir)
  "Create area51.lisp for a new project"
  (with-open-file (out (merge-pathnames *config-filename* dir)
                       :direction :output)
    (let ((*print-case* :downcase))
      (format out "(project ~s~%" name)
      (format out "  :version \"0.1.0\"~%")
      (format out "  :license \"MIT\"~%")
      (format out "  :entry-point \"main\")~%"))))

(defun scaffold-asd (name dir)
  "Create .asd system definition"
  (with-open-file (out (merge-pathnames (format nil "~a.asd" name) dir)
                       :direction :output)
    (let ((*print-case* :downcase))
      (format out "(defsystem ~s~%" name)
      (format out "  :version \"0.1.0\"~%")
      (format out "  :description \"\"~%")
      (format out "  :license \"MIT\"~%")
      (format out "  :depends-on ()~%")
      (format out "  :components ((:module \"src\"~%")
      (format out "                :components~%")
      (format out "                ((:file \"package\")~%")
      (format out "                 (:file \"main\" :depends-on (\"package\"))))))~%"))))

(defun scaffold-package (name dir)
  "Create package.lisp"
  (with-open-file (out (merge-pathnames "src/package.lisp" dir)
                       :direction :output)
    (let ((*print-case* :downcase))
      (format out "(defpackage #:~a~%" name)
      (format out "  (:use #:cl)~%")
      (format out "  (:export #:main))~%"))))

(defun scaffold-main (name dir)
  "Create main.lisp"
  (with-open-file (out (merge-pathnames "src/main.lisp" dir)
                       :direction :output)
    (let ((*print-case* :downcase))
      (format out "(in-package #:~a)~%~%" name)
      (format out "(defun main ()~%")
      (format out "  (format t \"Hello from ~a!~~%\"))~%" name))))

(defun scaffold-gitignore (dir)
  "Create .gitignore"
  (with-open-file (out (merge-pathnames ".gitignore" dir)
                       :direction :output)
    (format out "*.fasl~%")
    (format out "*.lx64fsl~%")
    (format out "*.dx64fsl~%")
    (format out "bin/~%")))

(defun cmd-new (args)
  "Create a new Common Lisp project"
  (when (null args)
    (format *error-output* "Usage: area51 new <project-name>~%")
    (uiop:quit 1))
  (let* ((name (first args))
         (dir (merge-pathnames
               (make-pathname :directory (list :relative name))
               (uiop:getcwd))))
    (when (probe-file dir)
      (format *error-output* "Error: directory ~a already exists~%" name)
      (uiop:quit 1))
    (ensure-directories-exist (merge-pathnames "src/" dir))
    (scaffold-config name dir)
    (scaffold-asd name dir)
    (scaffold-package name dir)
    (scaffold-main name dir)
    (scaffold-gitignore dir)
    (format t "Created new project: ~a~%" name)
    (format t "~%")
    (format t "  cd ~a~%" name)
    (format t "  area51 build~%")
    (format t "  area51 run~%")))
