(in-package #:area51)

(defparameter *version* "0.2.0")

(defun print-version ()
  (format t "area51 ~a~%" *version*))

(defun print-usage ()
  (format t "area51 - Common Lisp Package Manager~%")
  (format t "~%")
  (format t "Usage: area51 <command> [arguments]~%")
  (format t "~%")
  (format t "Commands:~%")
  (format t "  new <name>           Create a new project~%")
  (format t "  add <pkg> [options]  Add a dependency~%")
  (format t "  remove <pkg>         Remove a dependency~%")
  (format t "  install              Install dependencies~%")
  (format t "  build                Build standalone binary~%")
  (format t "  test                 Run tests~%")
  (format t "  run                  Run the project~%")
  (format t "  list                 List dependencies~%")
  (format t "  clean                Clean package cache~%")
  (format t "  upgrade              Upgrade area51 itself~%")
  (format t "~%")
  (format t "Options for 'add':~%")
  (format t "  (no flags)           Add from Quicklisp (default)~%")
  (format t "  --github user/repo   Add from GitHub~%")
  (format t "  --url URL            Add from git URL~%")
  (format t "  --ref REF            Pin to branch/tag/commit~%")
  (format t "~%")
  (format t "Examples:~%")
  (format t "  area51 add alexandria~%")
  (format t "  area51 add my-lib --github user/my-lib~%"))

(defun main ()
  (let ((args (uiop:command-line-arguments)))
    (if (null args)
        (print-usage)
        (let ((command (first args))
              (rest-args (rest args)))
          (handler-case
              (cond
                ((string= command "new")     (cmd-new rest-args))
                ((string= command "add")     (cmd-add rest-args))
                ((string= command "remove")  (cmd-remove rest-args))
                ((string= command "install") (cmd-install rest-args))
                ((string= command "build")   (cmd-build rest-args))
                ((string= command "test")    (cmd-test rest-args))
                ((string= command "run")     (cmd-run rest-args))
                ((string= command "list")    (cmd-list rest-args))
                ((string= command "clean")   (cmd-clean rest-args))
                ((string= command "upgrade") (cmd-upgrade rest-args))
                ((string= command "-v")      (print-version))
                ((string= command "help")    (print-usage))
                ((string= command "--help")  (print-usage))
                (t
                 (format *error-output* "Unknown command: ~a~%" command)
                 (print-usage)
                 (uiop:quit 1)))
            (error (e)
              (format *error-output* "Error: ~a~%" e)
              (uiop:quit 1)))))))
